#!/bin/bash

build() {

	#add_module 'bcachefs'
	add_binary "bcachefs"
	add_binary "fsck.bcachefs"

	add_runscript
}

help() {

	cat <<HELPEOF
This hook is for setting the bcachefs unlock prompt at boot
HELPEOF
}

# vim set ft=sh ts=4 sw=4 et:
